### ISSUE TITLE
项目启动编译报错

### ISSUE THREAD

**Issue by kakaoG** [JJJYY/mpvue-iview#1]
![image](https://user-images.githubusercontent.com/12584373/41711581-04ba78ac-757b-11e8-924d-020cac215c7a.png)
![image](https://user-images.githubusercontent.com/12584373/41711593-0b5f9a2a-757b-11e8-9c03-d8269f861a2e.png)

**Comment by jessejyang** [comment]
@zhichaoGuo ,更新下`import-weapp-component`，原因是插件没有处理好`windows`路径问题
