### ISSUE TITLE
最新mpvue模板引入iview无效

### ISSUE THREAD

**Issue by Pasoul** [JJJYY/mpvue-iview#10]
"mpvue": "^1.0.11"
"mpvue-loader": "^1.1.4"
1. 使用官方`vue init mpvue/mpvue-quickstart  project`创建工程
2. 引入插件 `yarn add import-weapp-component --dev`
3. 在webpack.base.conf.js配置：
`const ImportComponent = require("import-weapp-component");`
```
plugins: [
    new MpvuePlugin(),
    new ImportComponent(),
    new CopyWebpackPlugin(
      [
        {
          from: "**/*.json",
          to: ""
        }
      ],
      {
        context: "src/"
      }
    ),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, "../static"),
        to: path.resolve(__dirname, "../dist/static"),
        ignore: [".*"]
      }
    ])
  ]
```
4. 在pages/index创建main.json文件：
```
{
  "navigationBarTitleText": "Card 卡片",
  "usingComponents": {
    "i-card": "/iview/card/index"
  }
}

```
5. 在index/index.vue使用card组件：
```
<i-card title="卡片标题" extra="额外内容" thumb="https://i.loli.net/2017/08/21/599a521472424.jpg">
      <div slot="content">内容不错</div>
      <div slot="footer">尾部内容</div>
    </i-card>
```
6. 拷贝iview目录到项目根路径，执行`yarn run dev`,**并未在dist目录下看到拷贝的iview组件**，并且页面报错
![image](https://user-images.githubusercontent.com/22902187/44380909-79843e80-a540-11e8-944c-86735441d441.png)

**Comment by jessejyang** [comment]
`mpvue-loader`升级之后原来写在`main.js`中的 json，分离到了`main.json`直接 copy 过去的，目前不兼容。
谢谢反馈，今天刚发现。
http://mpvue.com/change-log/2018.7.24/#srcappjson

可以通过把小程序组件拷贝到 `static` 文件下引用小程序组件

**Comment by jikuodong** [comment]
大佬，可不可以写个mpvue引用iview webapp的demo?现在放到json 中，card等标签没有效果，不知道为什么？

**Comment by jikuodong** [comment]
终于搞明白了，原来组件引用需要在父组件中引用，自己json文件中引用没用,整整浪费我一天时间

**Comment by jessejyang** [comment]
这个项目就是我拿 iveiw 的官方 Demo 改的，不过版本比较旧，我今天测试的最新版修改了机制，你的可以？

**Comment by XiaoBaiRoadToGod** [comment]
@jikuodong 可以写一个例子吗

**Comment by jessejyang** [comment]
增加了对最新版本`mpvue-loader`的支持，增加了对引用原生页面的支持
