### ISSUE TITLE
mpvue 引入iview-weapp的action-sheet组件,点击选项无法获取选项索引

### ISSUE THREAD

**Issue by xianer0405** [JJJYY/mpvue-iview#2]
*** bug
mpvue 引入iview-weapp的action-sheet组件,点击选项无法获取选项索引
在上层的vue界面打印事件event对象, e.mp.detail和e.mp.currentTarget.dataset中都没有索引值.
![image](https://user-images.githubusercontent.com/3275868/42032764-40503a86-7b0d-11e8-9ad2-cff37ad5e0a3.png)

![image](https://user-images.githubusercontent.com/3275868/42032629-c4f5755e-7b0c-11e8-8bff-49d9b5a232b2.png)

**Comment by xianer0405** [comment]
在上层的vue界面选项的点击事件的回调函数内打印事件event对象, e.mp.detail和e.mp.currentTarget.dataset中都没有索引值.
代码如下:
handleClickItem1(e) {
  console.log(e)
  console.log('点击了选项' + index)
},

**Comment by xianer0405** [comment]
https://github.com/TalkingData/iview-weapp

**Comment by jessejyang** [comment]
这个我在`readme`有说明
