### ISSUE TITLE
开发工具显示正常，手机预览失败问题

### ISSUE THREAD

**Issue by aferica** [JJJYY/mpvue-iview#3]
项目使用开发工具使用正常，但是我点击预览后使用手机显示的时候所有样式都消失了，首页只剩下图标

**Comment by jessejyang** [comment]
@aferica 这个项目我是上线了的， 你可以搜索一下`MpiViewUI`，看下有没有问题，有问题的话可以把系统机型信息告诉我，我看能不能测试下

**Comment by aferica** [comment]
使用MpiViewUI没有问题 这就很尴尬了  我再试试

**Comment by jessejyang** [comment]
真机预览有什么问题么？
