### ISSUE TITLE
clone这个项目运行不了

### ISSUE THREAD

**Issue by keycz** [JJJYY/mpvue-iview#4]
未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

**Comment by jessejyang** [comment]
方便的话，把你从`clone`到在开发工具打开的步骤写下，或者说`npm start`报了什么错
谢谢

**Comment by keycz** [comment]
我用mpvuesimple-quickstart这个构件项目之后发现可以用了，谢谢！

**Comment by jessejyang** [comment]
按说应该`clone`下来就可以，没问题先关了
