### ISSUE TITLE
不支持修改样式吗？

### ISSUE THREAD

**Issue by fandudu** [JJJYY/mpvue-iview#5]
比如我想改变i-tab的宽度，用
.i-tabs-tab{
        width: 25%
 }修改无效，设置颜色也无效，难道只能传样式吗

**Comment by jessejyang** [comment]
`iview`基本每个组件都提供了一个`i-class`，
不过恐怕你并不能完整的依靠这一个`class`控制整个组件样式
其他的你可以在`iview`小程序官方示例测试下，我这个示例只是在`mpvue`的大框架下，把原生组件按需拷贝到输出目录，除了解决一些坑外(`readme`有说明)并没有对框架做任何修改
谢谢
