### ISSUE TITLE
很感谢！可用的！不过一个问题，如何在Vue组件中使用小程序的components呢？

### ISSUE THREAD

**Issue by gaogelucas** [JJJYY/mpvue-iview#6]

**Comment by jessejyang** [comment]
因为`mpvue`并非把`vue`组件编译为原生组件(不存在`json`文件)，而是用`template`实现，这个库并没有修改`mpvue`默认行为。
目前对使用了原生组件的`vue`组件必须在其被使用的`page`中引入
可以参考[例子](https://github.com/JJJYY/mpvue-iview/blob/master/src/pages/components/index.vue)
目前作用比较单一，仅仅是对组件的按需拷贝

**Comment by gaogelucas** [comment]
谢谢回复。我在尝试用Vue重写它了，新手上路
https://github.com/lucasphbs/mpvue-iview
