### ISSUE TITLE
i-input无法双向绑定，只能显示变量值

### ISSUE THREAD

**Issue by jifeilong9** [JJJYY/mpvue-iview#7]
![image](https://user-images.githubusercontent.com/24316291/43760702-781c1702-9a55-11e8-8cb3-b3db0566980d.png)
这么写，修改input后变量值不变

**Comment by jessejyang** [comment]
可以用`@change`去修改，`mpvue`与原生组件间目前无法使用`v-model`

**Comment by jifeilong9** [comment]
使用@change解决，感谢
