### ISSUE TITLE
您好，编译结果无法直接执行

### ISSUE THREAD

**Issue by julywind** [JJJYY/mpvue-iview#8]
我编译出来的结果缺文件，app.json是需要手写么？

**Comment by jessejyang** [comment]
不需要, 有没有报错信息?

**Comment by julywind** [comment]
没有报错信息，就是生成的文件夹里没有app.json文件
不过应该是我环境的问题，刚刚我用另外一个工程，也遇到了这个问题 不知道怎么回事

**Comment by jessejyang** [comment]
试下这个 https://github.com/Meituan-Dianping/mpvue/issues/840

**Comment by julywind** [comment]
可以了是新老vue-loader版本的问题，最新的mpvue里 不会用main.js的export生成json文件，而是直接有一个.json文件，直接改就行了，感谢!
