### ISSUE TITLE
编译无法完成

### ISSUE THREAD

**Issue by zyqq** [JJJYY/mpvue-iview#9]
![image](https://user-images.githubusercontent.com/15664576/44035749-c9869382-9f42-11e8-8c77-a3aa373f10c1.png)
安装了插件，但是编译时卡住了

**Comment by jessejyang** [comment]
重新`dev`或者`build`看看

**Comment by zyqq** [comment]
一样哇。用npm i -D import-weapp-component，然后在webpack.base.conf.js里引用插件了，对照你的对应源码也没错，然后在对应页面的main.js使用了usingComponents；
之前还报引用的组件路径错误我改过来了，之后npm run dev就是一直卡在这里

**Comment by jessejyang** [comment]
方便的话，能否提供下`webpack.base.conf.js`和`main.js`的代码？

**Comment by zyqq** [comment]
![image](https://user-images.githubusercontent.com/15664576/44036527-902a2eee-9f44-11e8-9b04-5a0e55d4d46b.png)
![image](https://user-images.githubusercontent.com/15664576/44036538-991d1f98-9f44-11e8-953c-71588d128db3.png)
以上是webpack.base.conf.js的，以下是main.js的
![image](https://user-images.githubusercontent.com/15664576/44036562-a8fedbc2-9f44-11e8-8c45-325f4700c7a8.png)

**Comment by jessejyang** [comment]
可以试试把插件去掉，再`npm run dev`，如果可以的话，恐怕只能提供个`Demo`给我了，目前不请求哪里有问题。

**Comment by zyqq** [comment]
卸掉编译编译就正常了，重新安装也没用。谢谢你这么晚还抽空回我

**Comment by jessejyang** [comment]
抱歉不太清楚问题出到哪，如果要使用原生组件还可以把组将放在`static`文件夹下面来引入试试，这样只是你要什么需要单独拷贝过去（也可以全部拷贝，只是会增大包体积）

**Comment by zyqq** [comment]
直接放在static目录下引用组件就可以了。貌似用不着你这插件？这样引入也没有什么麻烦，只是得放在static目录下而已

**Comment by jessejyang** [comment]
总的来说原理是一样的，都是复制，只是我这个插件会按照你引入的组件路径复制而非全部复制，而放在`static`文件夹下会全部复制（插件的作用相当于按需引入，而且不局限于`static`文件夹）

这个插件就是从`WebpackCopyPlugin`插件`fork`的

**Comment by zyqq** [comment]
666
